org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.9
enabled_platforms=fabric,forge,neoforge

archives_base_name=e4mc_minecraft
mod_version=5.4.1
maven_group=link.e4mc

architectury_version=4.11.93

fabric_loader_version=0.18.1
fabric_api_version=0.134.0+1.21.9

forge_version=1.21.9-59.0.5

neoforge_version=21.9.16-beta

quic_version=0.0.70.Final.e4mc

modrinthId=qANg5Jrr
curseforgeId=849519