org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.10
enabled_platforms=fabric

archives_base_name=e4mc_minecraft
mod_version=5.5.0
maven_group=link.e4mc

architectury_version=18.0.8

fabric_loader_version=0.16.5
fabric_api_version=0.138.3+1.21.10

forge_version=1.20.2-48.1.0

neoforge_version=21.10.63

quic_version=0.0.70.Final.e4mc

modrinthId=qANg5Jrr
curseforgeId=849519