name: Build the shit

on:
  workflow_dispatch:
  push:
    branches:
      - rererewrite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e4mc-builds
          path: |
            **/build/libs/*.jar
            !**/build/libs/*-sources.jar
